
5.34:
	g++ -Wall -o2 5.34.cpp -o 5.34 \
	-I/Users/liuxingchen/work/DataStructureCourse/DataStructureHomework/chapter3/lxc/ \

5.31:
	g++ -Wall -o2 5.31.cpp -o 5.31 \
	-I/Users/liuxingchen/work/DataStructureCourse/DataStructureHomework/chapter3/lxc/ \

thread_test:
	g++ -Wall -o2 thread_test.cpp -o thread_test \
	-I/Users/liuxingchen/work/DataStructureCourse/DataStructureHomework/chapter3/lxc/ 
5.29:
	g++ -Wall -o2 5.29.cpp -o 5.29 \
	-I/Users/liuxingchen/work/DataStructureCourse/DataStructureHomework/chapter3/lxc/ \

clean:
	rm 5.29
5.27:
	g++ -Wall -o2 5.27.cpp -o 5.27 \
	-I/Users/liuxingchen/work/DataStructureCourse/DataStructureHomework/chapter3/lxc/ \
5.26:
	g++ -Wall -o2 5.26.cpp -o 5.26 \
	-I/Users/liuxingchen/work/DataStructureCourse/DataStructureHomework/chapter3/lxc/ 
5.25:
	g++ -Wall -o2 5.25.cpp -o 5.25 \
	-I/Users/liuxingchen/work/DataStructureCourse/DataStructureHomework/chapter3/lxc/ 


testTLT:
	g++ -Wall -o2 testTLT.cpp -o testTLT \
	-I/Users/liuxingchen/work/DataStructureCourse/DataStructureHomework/chapter3/lxc/ 


git_up:
	@git add -A;git commit -m"homework update";git pull;git status;git push origin master
