use_area: use_area.cpp
	g++ -Wall -O2 -std=c++11 -I../how_to_library -L../how_to_library -o $@ $^ -lLXCMATH
# type this in cmd line, to link .so
#LD_LIBRARY_PATH=$LD_LIBRARY_PATH:../how_to_library(valid for Linux)
#install_name_tool -change libLXCMATH.so ../how_to_library/libLXCMATH.so ./use_area (valid for mac_Unix) 
