CC=g++
CFLAGS = -Wall -O2 -std=c++11 -I../../DataStructureHomework/chapter3/lxc/
#text_book_1.1: text_book_1.1.cpp
#       $(CC) $(CFLAGS) -o $@ 

#math_test: math_test.cpp 
#	$(CC) $(CFLAGS) -o $@  $^
tournament_sort:tournament_sort.cpp 
	$(CC) $(CFLAGS) -o $@  $^


msd_radix:msd_radix.cpp 
	$(CC) $(CFLAGS) -o $@  $^


bucket_sort:bucket_sort.cpp 
	$(CC) $(CFLAGS) -o $@  $^

binary_insert_sort:binary_insert_sort.cpp 
	$(CC) $(CFLAGS) -o $@  $^

shell_sort:shell_sort.cpp 
	$(CC) $(CFLAGS) -o $@  $^

quick_sort:quick_sort.cpp 
	$(CC) $(CFLAGS) -o $@  $^
heap_sort: heap_sort.cpp 
	$(CC) $(CFLAGS) -o $@  $^
merger_sort: merger_sort.cpp 
	$(CC) $(CFLAGS) -o $@  $^

git_up:
	@git add -A;git commit -m"general list(construction function)";git pull;git status;git push origin master
