CC = g++  
CFLAGS = -Wall -O2 -std=c++11 -I/Users/liuxingchen/work/DataStructureCourse/DataStructureHomework/common_library # 指定头文件首先搜索的路径

Filename=gen_list_test
End=.cpp
$(Filename): $(Filename)$(End) /Users/liuxingchen/work/DataStructureCourse/DataStructureHomework/common_library/mystd.cpp 
	@$(CC) $(CFLAGS) -o $@  $^ #-I ../../DataStructureHomework/chapter2
