LINKS = ../../DataStructureHomework/common_library/mystd.cpp
LIBS = -I../../DataStructureHomework/common_library/
CC = g++
CFLAGS = -Wall -O2 -std=c++11

test_heap: test_heap.cpp $(LINKS)
	$(CC) $(CFLAGS) $(LIBS) -o $@ $^
test_merge: test_merge.cpp $(LINKS)
	$(CC) $(CFLAGS) $(LIBS) -o $@ $^
test_quick: test_quick.cpp $(LINKS)
	$(CC) $(CFLAGS) $(LIBS) -o $@ $^
test_time: test_time.cpp $(LINKS)
	$(CC) $(CFLAGS) $(LIBS) -o $@ $^
test_insert: test_insert.cpp $(LINKS)
	$(CC) $(CFLAGS) $(LIBS) -o $@ $^
